// GENERATED by tools/client-emit.mts from spec/model.ts — do not edit by hand.
//
// HAND-STATED TYPES (substrat.client.types). These schemas have no inferable input
// type — a `z.preprocess` infers `unknown` by construction — so the type below was
// decided by a person, not derived, and is not checked against the schema:
//   mirrorChoice.anchors → [string, string]
//   mirrorChoice.candidates → [{ x: number; y: number }, { x: number; y: number }]
//
// Re-emit with `pnpm lint:client`; CI runs `pnpm lint:client --check` and fails on
// drift, so the client cannot fall behind the model the way a hand-written one did.
//
// Standalone on purpose: no imports, so the browser bundle carries no schema library
// and `tools/declared-deps.mjs` has nothing to object to.

/** A failed request. `status` is the interesting field — 403 is the permission model answering. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
    readonly body: unknown,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

/**
 * One page of a paged read, reassembled from the response.
 *
 * The BODY is the entries and always was; the walk rides in headers (#829), which is
 * what let paging be adopted without renaming a live endpoint's response. This puts
 * the two back together so a caller sees a page rather than a header protocol.
 *
 * `next` is an absolute URL to FOLLOW (RFC 8288), not a cursor to reassemble — this
 * request's filters and page size travel with it. Its absence is how the walk ends.
 */
export interface Paged<T> {
  entries: T[];
  /** Hand back to `follow()`. `null` when there is no next page. */
  next: string | null;
  /** From `X-Total-Count`, and only for a read that declares `total`. */
  total: number | null;
}

export interface ClientOptions {
  /** Prefixed to every declared path. Matches `mountOperations`' own default. */
  baseUrl?: string;
  /** Per-request headers — an auth token, or this demo's `x-principal` persona seam. */
  headers?: () => Record<string, string>;
  /** Injectable so the client works under a test harness, not only in a browser. */
  fetch?: typeof globalThis.fetch;
  /**
   * Pull a message out of an error body.
   *
   * The one thing here the model does NOT declare: a vertical picks its error
   * envelope in its own `app.onError`, so this is a best effort over the shapes in
   * use — `{ error }`, and problem+json's `detail`/`title` — and an app that
   * answers something else says so here rather than being guessed at.
   */
  errorMessage?: (body: unknown, response: Response) => string | undefined;
}

function defaultErrorMessage(body: unknown): string | undefined {
  if (typeof body !== 'object' || body === null) return undefined;
  const b = body as Record<string, unknown>;
  for (const key of ['error', 'detail', 'title', 'message']) {
    if (typeof b[key] === 'string') return b[key] as string;
  }
  return undefined;
}


/** `garden_sites` — declared in spec/model.ts. */
export interface Site {
  id: string;
  name: string;
  datum_note: string | null;
  created_at: string;
}

/** `garden_points` — declared in spec/model.ts. */
export interface Point {
  id: string;
  site_id: string;
  seq: number;
  name: string;
  elevation_m: number | null;
  x: number | null;
  y: number | null;
  status: "named" | "measured" | "placed";
  side: number | null;
  locked: number;
  note: string | null;
  created_at: string;
}

/** `garden_measurements` — declared in spec/model.ts. */
export interface Measurement {
  id: string;
  site_id: string;
  point_a: string;
  point_b: string;
  distance_m: number;
  note: string | null;
  created_at: string;
}

/** `garden_constraints` — declared in spec/model.ts. */
export interface Constraint {
  id: string;
  site_id: string;
  kind: "right-angle" | "parallel" | "equal-length" | "colinear";
  points_json: string;
  created_at: string;
}

/** `garden_features` — declared in spec/model.ts. */
export interface Feature {
  id: string;
  site_id: string;
  type: "retention-wall" | "pool" | "terrace" | "stairs" | "house" | "fence" | "bed" | "path";
  name: string;
  closed: number;
  props_json: string;
  created_at: string;
}

/** `garden_feature_vertices` — declared in spec/model.ts. */
export interface FeatureVertex {
  feature_id: string;
  seq: number;
  point_id: string;
  curved_to_next: number;
}

/** `garden_species` — declared in spec/model.ts. */
export interface Species {
  id: string;
  common_name: string;
  latin_name: string | null;
  category: "tree" | "shrub" | "hedge" | "perennial" | "climber";
  mature_canopy_m: number | null;
  mature_height_m: number | null;
  years_to_mature: number | null;
  created_at: string;
}

/** `garden_plants` — declared in spec/model.ts. */
export interface Plant {
  id: string;
  site_id: string;
  point_id: string;
  species_id: string;
  label: string | null;
  planted_on: string | null;
  note: string | null;
  created_at: string;
}

/** `solveReport` — a published schema, not a stored row. */
export interface SolveReport {
  siteId: string;
  moved: ({ pointId: string; from: { x: number; y: number } | null; to: { x: number; y: number }; deltaCm: number })[];
  placed: string[];
  unplaced: { id: string; distances: number }[];
  needsSide: MirrorChoice[];
  measurementResidualsCm: Record<string, number>;
  constraintResidualsCm: Record<string, number>;
  rmsCm: number;
}

/** `sitePayload` — a published schema, not a stored row. */
export interface SitePayload {
  site: Site;
  points: Point[];
  measurements: Measurement[];
  constraints: ({ id: string; site_id: string; kind: "right-angle" | "parallel" | "equal-length" | "colinear"; points_json: string; created_at: string; points: string[] })[];
  features: ({ id: string; site_id: string; type: "retention-wall" | "pool" | "terrace" | "stairs" | "house" | "fence" | "bed" | "path"; name: string; closed: number; props_json: string; created_at: string; vertices: { point_id: string; seq: number; curved_to_next: number }[]; props: Record<string, unknown> })[];
  plants: ({ id: string; site_id: string; point_id: string; species_id: string; label: string | null; planted_on: string | null; note: string | null; created_at: string; species: Species })[];
  solve: SolveReport;
}

/** `mirrorChoice` — a published schema, not a stored row. */
export interface MirrorChoice {
  id: string;
  anchors: [string, string];
  candidates: [{ x: number; y: number }, { x: number; y: number }];
}

/** `siteSummary` — a published schema, not a stored row. */
export interface SiteSummary {
  id: string;
  name: string;
  datum_note: string | null;
  created_at: string;
  points: number;
  measurements: number;
  features: number;
  plants: number;
}

/** Every operation this vertical binds to HTTP, one method each. */
export interface TriangleClient {
  /**
   * Apply a constraint (right angle, parallel, equal length, colinear)
   *
   * `POST /sites/{siteId}/constraints` — `garden/add-constraint`
   */
  addConstraint(input: { siteId: string; kind: "right-angle" | "parallel" | "equal-length" | "colinear"; pointIds: string[] }): Promise<{ constraintId: string; constraint: Constraint; solve: SolveReport }>;

  /**
   * Record a tape pull between two points, in centimeters
   *
   * `POST /sites/{siteId}/measurements` — `garden/add-measurement`
   */
  addMeasurement(input: { siteId: string; pointA: string; pointB: string; distanceCm: number; note?: string }): Promise<{ measurementId: string; measurement: Measurement; solve: SolveReport }>;

  /**
   * Plant a species at a point
   *
   * `POST /sites/{siteId}/plants` — `garden/add-plant`
   */
  addPlant(input: { siteId: string; pointId: string; speciesId: string; label?: string; plantedOn?: string; note?: string }): Promise<Plant>;

  /**
   * Pick which of the two mirror positions a two-distance point is on
   *
   * `POST /points/{pointId}/side` — `garden/choose-side`
   */
  chooseSide(input: { pointId: string; side: 1 | -1 }): Promise<{ pointId: string; point: Point; solve: SolveReport }>;

  /**
   * Draw a feature through an ordered run of points
   *
   * `POST /sites/{siteId}/features` — `garden/create-feature`
   */
  createFeature(input: { siteId: string; type: "retention-wall" | "pool" | "terrace" | "stairs" | "house" | "fence" | "bed" | "path"; name: string; closed?: boolean; vertices: { pointId: string; curvedToNext?: boolean }[]; props?: Record<string, unknown> }): Promise<Feature>;

  /**
   * Name a survey point (the first becomes the origin, the second the baseline)
   *
   * `POST /sites/{siteId}/points` — `garden/create-point`
   */
  createPoint(input: { siteId: string; name: string; elevationM?: number; note?: string }): Promise<Point>;

  /**
   * Create a garden
   *
   * `POST /sites` — `garden/create-site`
   */
  createSite(input: { name: string; datumNote?: string }): Promise<Site>;

  /**
   * Remove a constraint; the survey re-solves without it
   *
   * `DELETE /constraints/{constraintId}` — `garden/delete-constraint`
   */
  deleteConstraint(input: { constraintId: string }): Promise<{ deleted: string; solve: SolveReport }>;

  /**
   * Delete a feature (its points stay)
   *
   * `DELETE /features/{featureId}` — `garden/delete-feature`
   */
  deleteFeature(input: { featureId: string }): Promise<{ deleted: string }>;

  /**
   * Delete a tape pull; the survey re-solves from what survives
   *
   * `DELETE /measurements/{measurementId}` — `garden/delete-measurement`
   */
  deleteMeasurement(input: { measurementId: string }): Promise<{ deleted: string; solve: SolveReport }>;

  /**
   * Delete a point and every tape pull and constraint that used it
   *
   * `DELETE /points/{pointId}` — `garden/delete-point`
   */
  deletePoint(input: { pointId: string }): Promise<{ deleted: string; solve: SolveReport }>;

  /**
   * The garden as ASCII DXF (R12): points with Z = elevation, one layer per feature type, mature canopies
   *
   * `GET /sites/{siteId}/dxf` — `garden/export-dxf`
   */
  exportDxf(input: { siteId: string }): Promise<{ siteId: string; filename: string; dxf: string }>;

  /**
   * A garden in full: points, tape pulls, constraints, features, plants and the current solve
   *
   * `GET /sites/{siteId}` — `garden/get-site`
   */
  getSite(input: { siteId: string }): Promise<SitePayload>;

  /**
   * The gardens in this tenant, with their counts
   *
   * `GET /sites` — `garden/list-sites`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listSites(): Promise<Paged<SiteSummary>>;

  /**
   * The species library, alphabetical
   *
   * `GET /species` — `garden/list-species`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listSpecies(): Promise<Paged<Species>>;

  /**
   * Dry-run a constraint: what would it move, and by how much
   *
   * `POST /sites/{siteId}/constraints/preview` — `garden/preview-constraint`
   */
  previewConstraint(input: { siteId: string; kind: "right-angle" | "parallel" | "equal-length" | "colinear"; pointIds: string[] }): Promise<SolveReport>;

  /**
   * Remove a plant
   *
   * `DELETE /plants/{plantId}` — `garden/remove-plant`
   */
  removePlant(input: { plantId: string }): Promise<{ deleted: string }>;

  /**
   * Re-solve the whole survey and persist the coordinates
   *
   * `POST /sites/{siteId}/solve` — `garden/solve`
   */
  solve(input: { siteId: string }): Promise<SolveReport>;

  /**
   * An entity's event history off the audit spine — why did the pool move 12 cm last Tuesday
   *
   * `GET /entities/{entityType}/{entityId}/timeline` — `garden/timeline`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  timeline(input: { entityType: string; entityId: string }): Promise<Paged<({ id: string; type: string; occurredAt: string; actor: string | { system: string } | { connection: string }; payload: unknown; authorization: { permission: string; grant?: string }[] | null; impersonation: { session: string; by: string } | null; piiClass: "none" | "pseudonymous" | "direct"; subjectId: string | null })>>;

  /**
   * Rename a feature, open or close it, retrace its run or change its properties
   *
   * `PATCH /features/{featureId}` — `garden/update-feature`
   *
   * Concurrency-checked over `feature`. The tag this answers with is
   * remembered and sent as `If-Match` on the next write to the same entity, so a
   * write that would overwrite someone else's change fails with 412 instead.
   */
  updateFeature(input: { featureId: string; name?: string; closed?: boolean; vertices?: { pointId: string; curvedToNext?: boolean }[]; props?: Record<string, unknown> }): Promise<Feature>;

  /**
   * Rename a point, set its elevation or note, or lock its position
   *
   * `PATCH /points/{pointId}` — `garden/update-point`
   *
   * Concurrency-checked over `point`. The tag this answers with is
   * remembered and sent as `If-Match` on the next write to the same entity, so a
   * write that would overwrite someone else's change fails with 412 instead.
   */
  updatePoint(input: { pointId: string; name?: string; elevationM?: number | null; locked?: boolean; note?: string | null }): Promise<{ pointId: string; point: Point; solve: SolveReport }>;

  /**
   * Add a species to the library, or update one by id
   *
   * `PUT /species` — `garden/upsert-species`
   */
  upsertSpecies(input: { id?: string; commonName: string; latinName?: string; category: "tree" | "shrub" | "hedge" | "perennial" | "climber"; matureCanopyM?: number; matureHeightM?: number; yearsToMature?: number }): Promise<Species>;

  /**
   * The caller's role hint for the app shell, derived from the same two grants every operation checks
   *
   * `GET /whoami` — `garden/whoami`
   */
  whoami(): Promise<{ role: "garden-owner" | "garden-viewer" }>;

  /**
   * The entity tags this client is holding, keyed `entityType:id` (#129).
   *
   * Populated from every concurrency-checked response and sent back as
   * `If-Match` on the next write to that entity — an app writes no header code.
   * Exposed rather than hidden so it can be inspected in a devtools session and
   * cleared when a screen is abandoned; a stale tag causes a 412, never a silent
   * overwrite, so clearing it is safe and keeping it is safe.
   */
  readonly versions: Map<string, string>;

  /**
   * Fetch the next page of any paged read, given a previous page's `next`.
   *
   * One method for every paged read rather than one per read: `next` is a URL that
   * already carries the filters, so there is nothing left for a caller to restate.
   */
  follow<T>(next: string): Promise<Paged<T>>;
}

/**
 * The plumbing below is deliberately untyped against the interface above, and cast
 * once at the end.
 *
 * `send` cannot know an operation's return type — it has a `Response`, not a schema
 * — so every method would otherwise need its own `as` and the file would carry
 * fourteen casts instead of one. The interface is what a caller sees, and it IS
 * derived from the model; this is the seam where a runtime that speaks `unknown`
 * meets it.
 */
type Args = Record<string, unknown>;

const omit = (input: Record<string, unknown>, keys: string[]): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(input ?? {})) if (!keys.includes(k)) out[k] = v;
  return out;
};

/** Declared fields become a query string; `undefined` is absent rather than the string "undefined". */
const query = (values: Record<string, unknown> | undefined): string => {
  if (!values) return '';
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(values)) {
    if (v === undefined || v === null) continue;
    params.set(k, String(v));
  }
  const s = params.toString();
  return s ? `?${s}` : '';
};

/**
 * The `rel="next"` URL out of an RFC 8288 `Link` header, or null.
 *
 * Only `next` is looked for because only `next` is sent: keyset paging walks one
 * way and does not know its own offset, so there is no `prev`, `first` or `last`
 * to honour. A header naming some other relation is not this walk's.
 */
const nextFrom = (header: string | null): string | null => {
  if (!header) return null;
  for (const part of header.split(',')) {
    const match = /^\s*<([^>]+)>\s*;\s*(.+)$/.exec(part);
    if (match && /rel\s*=\s*"?next"?/.test(match[2] as string)) return match[1] as string;
  }
  return null;
};

export function createClient(options: ClientOptions = {}): TriangleClient {
  const baseUrl = options.baseUrl ?? '/api';
  const doFetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  const readMessage = options.errorMessage ?? defaultErrorMessage;
  /** #129: entity tags seen on this client, keyed `entityType:id`. */
  const versions = new Map<string, string>();

  /** One request, against a path that is ALREADY prefixed and query-stringed. */
  const raw = async (fullPath: string, method: string, body: unknown, extra?: Record<string, string>): Promise<Response> => {
    const hasBody = body !== undefined && method !== 'GET' && method !== 'DELETE';
    return await doFetch(fullPath, {
      method,
      headers: {
        ...(hasBody ? { 'content-type': 'application/json' } : {}),
        ...(options.headers?.() ?? {}),
        ...(extra ?? {}),
      },
      ...(hasBody ? { body: JSON.stringify(body) } : {}),
    });
  };

  const parse = async (res: Response): Promise<unknown> => {
    const text = await res.text();
    const body: unknown = text ? JSON.parse(text) : null;
    if (!res.ok) throw new ApiError(res.status, readMessage(body, res) ?? res.statusText, body);
    return body;
  };

  const send = async (path: string, method: string, body: unknown, params: unknown): Promise<unknown> =>
    await parse(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  /**
   * A concurrency-checked call (#129): remember the tag a read hands back, send it
   * as `If-Match` on the next write to that same entity.
   *
   * This is what makes the guarantee reachable without the app writing header code.
   * The tag is per (entity type, id) rather than global — two facilities being
   * edited in two tabs do not share one — and it lives on the CLIENT INSTANCE, so a
   * page reload starts empty and the first write after it simply goes unconditional
   * until something has been read.
   *
   * **A 412 evicts the tag rather than replacing it with the current one.** The
   * tempting behaviour is to re-read and retry automatically; that would overwrite
   * whatever change caused the refusal, which is the lost update this exists to
   * prevent. Evicting means the app's own re-read is what re-arms the guard, and
   * until it happens the next write is unconditional — visibly wrong rather than
   * quietly wrong.
   *
   * `versions` is exposed on the client so an app can inspect or clear it. Nothing
   * here is hidden state a caller cannot reach.
   */
  const guarded = async (
    entityType: string,
    entityId: unknown,
    path: string,
    method: string,
    body: unknown,
    params: unknown,
  ): Promise<unknown> => {
    const key = `${entityType}:${String(entityId)}`;
    const held = versions.get(key);
    const res = await raw(
      `${baseUrl}${path}${query(params as Record<string, unknown>)}`,
      method,
      body,
      held !== undefined && method !== 'GET' ? { 'If-Match': held } : undefined,
    );
    if (res.status === 412) versions.delete(key);
    const parsed = await parse(res);
    // Read AFTER `parse`, which throws on a failure — a tag from an error response
    // describes nothing the caller now holds.
    const tag = res.headers.get('ETag');
    if (tag) versions.set(key, tag);
    return parsed;
  };

  /**
   * A paged read: the entries come from the body, the walk from the headers.
   *
   * A cross-origin caller reads neither header without `Access-Control-Expose-Headers`,
   * and the symptom is not an error — it is a list that looks like it has one page. Under
   * a same-origin dev proxy (this demo) or a same-origin deployment, both are readable.
   */
  const readPage = async (res: Response): Promise<Paged<unknown>> => {
    const entries = (await parse(res)) as unknown[];
    const total = res.headers.get('X-Total-Count');
    return { entries, next: nextFrom(res.headers.get('Link')), total: total === null ? null : Number(total) };
  };

  const page = async (path: string, method: string, body: unknown, params: unknown): Promise<Paged<unknown>> =>
    await readPage(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  return {
    addConstraint: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/constraints`, "POST", omit(input, ["siteId"]), undefined),
    addMeasurement: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/measurements`, "POST", omit(input, ["siteId"]), undefined),
    addPlant: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/plants`, "POST", omit(input, ["siteId"]), undefined),
    chooseSide: (input: Args) =>
      send(`/points/${encodeURIComponent(String(input.pointId))}/side`, "POST", omit(input, ["pointId"]), undefined),
    createFeature: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/features`, "POST", omit(input, ["siteId"]), undefined),
    createPoint: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/points`, "POST", omit(input, ["siteId"]), undefined),
    createSite: (input: Args) =>
      send("/sites", "POST", input, undefined),
    deleteConstraint: (input: Args) =>
      send(`/constraints/${encodeURIComponent(String(input.constraintId))}`, "DELETE", undefined, omit(input, ["constraintId"])),
    deleteFeature: (input: Args) =>
      send(`/features/${encodeURIComponent(String(input.featureId))}`, "DELETE", undefined, omit(input, ["featureId"])),
    deleteMeasurement: (input: Args) =>
      send(`/measurements/${encodeURIComponent(String(input.measurementId))}`, "DELETE", undefined, omit(input, ["measurementId"])),
    deletePoint: (input: Args) =>
      send(`/points/${encodeURIComponent(String(input.pointId))}`, "DELETE", undefined, omit(input, ["pointId"])),
    exportDxf: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/dxf`, "GET", undefined, omit(input, ["siteId"])),
    getSite: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}`, "GET", undefined, omit(input, ["siteId"])),
    listSites: () =>
      page("/sites", "GET", undefined, undefined),
    listSpecies: () =>
      page("/species", "GET", undefined, undefined),
    previewConstraint: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/constraints/preview`, "POST", omit(input, ["siteId"]), undefined),
    removePlant: (input: Args) =>
      send(`/plants/${encodeURIComponent(String(input.plantId))}`, "DELETE", undefined, omit(input, ["plantId"])),
    solve: (input: Args) =>
      send(`/sites/${encodeURIComponent(String(input.siteId))}/solve`, "POST", omit(input, ["siteId"]), undefined),
    timeline: (input: Args) =>
      page(`/entities/${encodeURIComponent(String(input.entityType))}/${encodeURIComponent(String(input.entityId))}/timeline`, "GET", undefined, omit(input, ["entityType","entityId"])),
    updateFeature: (input: Args) =>
      guarded("feature", input.featureId, `/features/${encodeURIComponent(String(input.featureId))}`, "PATCH", omit(input, ["featureId"]), undefined),
    updatePoint: (input: Args) =>
      guarded("point", input.pointId, `/points/${encodeURIComponent(String(input.pointId))}`, "PATCH", omit(input, ["pointId"]), undefined),
    upsertSpecies: (input: Args) =>
      send("/species", "PUT", input, undefined),
    whoami: () =>
      send("/whoami", "GET", undefined, undefined),
    versions,
    follow: async (next: string) => {
      // The link names the API's OWN origin, which under a dev proxy is not the origin
      // this page was served from. So the path is kept and the origin is taken from
      // whatever this client was configured to talk to: relative for a browser, which
      // keeps the request same-origin, absolute for a harness that has no page.
      const link = new URL(next, 'http://substrat.invalid');
      const target = /^https?:\/\//.test(baseUrl)
        ? new URL(link.pathname + link.search, baseUrl).href
        : link.pathname + link.search;
      return await readPage(await raw(target, 'GET', undefined));
    },
  } as unknown as TriangleClient;
}
